# Generated by Django 3.2.25 on 2024-10-21 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FinancialData',
            new_name='StockData',
        ),
    ]
